name: filtering
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.7
    - pip
    - pytest
    - numpy
    - pandas
    - jupyter
    - scipy
    - matplotlib
    - scikit-image
    - opencv
    #- pip:
